### PR TITLE
Ensure upcoming/experimental features are enabled on all targets.

### PR DESCRIPTION
**Pull request by thomasvl**
Borrowed the idea from some other apple projects, this way there is less boilerplate in the file, hopefully making maintenance a little easier.

### CODE REVIEW

**Review by tbkka — APPROVED** [review]
Nice cleanup!

**Comment by thomasvl** [comment]
> Nice cleanup!

Thanks, can't take credit since it was in other packages.

And I just realized I didn't have everything in this, so updating.

Also need to figure out what conformance failed on the other PR, it passes locally with 5.9.2 on macOS.

**Comment by thomasvl** [comment]
> Also need to figure out what conformance failed on the other PR, it passes locally with 5.9.2 on macOS.

Yea, I guess this comes down to Linux differences in Foundation?

**Comment by thomasvl** [comment]
I've added a commit to fix up Sources/Conformance for the problems on linux.  PTAL.

**Review by tbkka — APPROVED** [review]

**Pull request merged**
