### PR TITLE
Add 5.4 testing.

### PR DESCRIPTION
**Pull request by thomasvl**
Move conformance test to 5.4 since it is the latest.

### CODE REVIEW

**Comment by thomasvl** [comment]
@Lukasa @tbkka - Any ideas on the _release_ sanitizer builds failing?  It is using `image: swift:bionic` so that should be the new 5.4 release.  I thought I had all the SwiftPM flags needed.

**Comment by Lukasa** [comment]
```
error: fatalError
```

Thanks Swift, not terribly helpful there. Let me see if I can reproduce this locally.

**Comment by Lukasa** [comment]
Great, reproduces locally with that docker image. I'll see if I can get some more useful information.

**Comment by thomasvl** [comment]
Great, thanks.  https://swift.org/download/ still lists all the images as coming soon, so maybe there is something up with them, but I was a little worried somethings up with 5.4 on linux in general.

Actually, I'll pull down the new Xcode and the swift.org toolchain for macOS to confirm those are working.

**Comment by Lukasa** [comment]
Building with verbose turned on suggests that we're failing at the link stage:

```
/usr/bin/swiftc -sanitize=thread -g -L /code/.build/x86_64-unknown-linux-gnu/release -o /code/.build/x86_64-unknown-linux-gnu/release/protoc-gen-swift -module-name protoc_gen_swift -emit-executable -Xlinker '-rpath=$ORIGIN' @/code/.build/x86_64-unknown-linux-gnu/release/protoc-gen-swift.product/Objects.LinkFileList -target x86_64-unknown-linux-gnu -enable-testing -L /usr/lib
/usr/bin/swiftc -sanitize=thread -g -L /code/.build/x86_64-unknown-linux-gnu/release -o /code/.build/x86_64-unknown-linux-gnu/release/Conformance -module-name Conformance -emit-executable -Xlinker '-rpath=$ORIGIN' @/code/.build/x86_64-unknown-linux-gnu/release/Conformance.product/Objects.LinkFileList -target x86_64-unknown-linux-gnu -enable-testing -L /usr/lib
error: fatalError
```

I'm highly suspicious of `-enable-testing` here.

**Comment by thomasvl** [comment]
Yea, I had to add that because of the `@testable import` usage.

**Comment by Lukasa** [comment]
I figured. I'm not suspicious of it because it's unreasonable, but because I can imagine it getting missed in a testing matrix.

**Comment by Lukasa** [comment]
I'm going to grab a core file to get a backtrace to find exactly which process is crashing and where.

**Comment by Lukasa** [comment]
Nice straightforward backtrace:

```
(lldb) bt
* thread #1, name = 'swift-frontend', stop reason = signal SIGABRT
  * frame #0: 0x00007f8ac7ae1fb7 libc.so.6`raise + 199
    frame #1: 0x00007f8ac7ae39fb libc.so.6`abort + 539
    frame #2: 0x00000000012e5b2d swift-frontend`(anonymous namespace)::SILVerifier::_require(bool, llvm::Twine const&, std::function<void ()> const&) + 1725
    frame #3: 0x0000000001306a45 swift-frontend`(anonymous namespace)::SILVerifier::visitSILInstruction(swift::SILInstruction*) + 3077
    frame #4: 0x00000000012f8d08 swift-frontend`swift::SILInstructionVisitor<(anonymous namespace)::SILVerifier, void>::visit(swift::SILInstruction*) + 57896
    frame #5: 0x00000000012ea4ee swift-frontend`(anonymous namespace)::SILVerifier::visitSILBasicBlock(swift::SILBasicBlock*) + 1438
    frame #6: 0x00000000012e89f6 swift-frontend`(anonymous namespace)::SILVerifier::visitSILFunction(swift::SILFunction*) + 9990
    frame #7: 0x00000000012e0d5e swift-frontend`swift::SILFunction::verify(bool) const + 62
    frame #8: 0x0000000000fa06db swift-frontend`(anonymous namespace)::OwnershipModelEliminator::run() + 155
    frame #9: 0x0000000000b0b7b2 swift-frontend`swift::SILPassManager::runPassOnFunction(unsigned int, swift::SILFunction*) + 1650
    frame #10: 0x0000000000b0c631 swift-frontend`swift::SILPassManager::runFunctionPasses(unsigned int, unsigned int) + 1185
    frame #11: 0x0000000000b0f4fe swift-frontend`swift::SILPassManager::execute() + 590
    frame #12: 0x0000000000b09bb8 swift-frontend`swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 56
    frame #13: 0x0000000000b09b6b swift-frontend`swift::ExecuteSILPipelineRequest::evaluate(swift::Evaluator&, swift::SILPipelineExecutionDescriptor) const + 59
    frame #14: 0x0000000000b26e2a swift-frontend`swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) + 26
    frame #15: 0x0000000000b14aa1 swift-frontend`llvm::Expected<swift::ExecuteSILPipelineRequest::OutputType> swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest>(swift::ExecuteSILPipelineRequest const&) + 465
    frame #16: 0x0000000000b09d85 swift-frontend`swift::executePassPipelinePlan(swift::SILModule*, swift::SILPassPipelinePlan const&, bool, swift::irgen::IRGenModule*) + 69
    frame #17: 0x0000000000b1732f swift-frontend`swift::runSILOptimizationPasses(swift::SILModule&) + 143
    frame #18: 0x00000000006a15bd swift-frontend`swift::CompilerInstance::performSILProcessing(swift::SILModule*) + 637
    frame #19: 0x000000000051c13d swift-frontend`performCompileStepsPostSILGen(swift::CompilerInstance&, std::unique_ptr<swift::SILModule, std::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 877
    frame #20: 0x000000000051bb7c swift-frontend`performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 524
    frame #21: 0x0000000000510710 swift-frontend`swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 5664
    frame #22: 0x000000000049be53 swift-frontend`main + 883
    frame #23: 0x00007f8ac7ac4bf7 libc.so.6`__libc_start_main + 231
    frame #24: 0x000000000049b96a swift-frontend`_start + 42
```

**Comment by Lukasa** [comment]
So this seems like the SILVerifier is crashing while we're running an ownership model elimination pass, possibly because the optimisation is unsound.

**Comment by Lukasa** [comment]
I'm not sure why we're not getting better debug output from Swift in the Linux docker images here, though.

**Comment by thomasvl** [comment]
Looks like if I use the swift.org toolchain on macOS I can repo it also:

```
❯ xcrun --toolchain swift swift test -c release --sanitize=address -Xswiftc -enable-testing
[7/9] Compiling SwiftProtobufPluginLibraryTests Descriptor+TestHelpers.swift
error: fatalError
```

**Comment by thomasvl** [comment]
With `-v`, the last lines:

```
/Library/Developer/Toolchains/swift-5.4-RELEASE.xctoolchain/usr/bin/swiftc -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -sanitize=address -g -L /Users/thomasvl/src/github/swift-protobuf/.build/x86_64-apple-macosx/release -o /Users/thomasvl/src/github/swift-protobuf/.build/x86_64-apple-macosx/release/protoc-gen-swift -module-name protoc_gen_swift -emit-executable -Xlinker -rpath -Xlinker @loader_path @/Users/thomasvl/src/github/swift-protobuf/.build/x86_64-apple-macosx/release/protoc-gen-swift.product/Objects.LinkFileList -Xlinker -rpath -Xlinker /Library/Developer/Toolchains/swift-5.4-RELEASE.xctoolchain/usr/lib/swift/macosx -target x86_64-apple-macosx10.10 -enable-testing -L /Library/Developer/Toolchains/swift-5.4-RELEASE.xctoolchain/usr/lib
/Library/Developer/Toolchains/swift-5.4-RELEASE.xctoolchain/usr/bin/swiftc -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -sanitize=address -g -L /Users/thomasvl/src/github/swift-protobuf/.build/x86_64-apple-macosx/release -o /Users/thomasvl/src/github/swift-protobuf/.build/x86_64-apple-macosx/release/Conformance -module-name Conformance -emit-executable -Xlinker -rpath -Xlinker @loader_path @/Users/thomasvl/src/github/swift-protobuf/.build/x86_64-apple-macosx/release/Conformance.product/Objects.LinkFileList -Xlinker -rpath -Xlinker /Library/Developer/Toolchains/swift-5.4-RELEASE.xctoolchain/usr/lib/swift/macosx -target x86_64-apple-macosx10.10 -enable-testing -L /Library/Developer/Toolchains/swift-5.4-RELEASE.xctoolchain/usr/lib
error: fatalError
```

**Comment by Lukasa** [comment]
https://bugs.swift.org/browse/SR-14550

**Comment by Lukasa** [comment]
FWIW the sanitisers seem to be a red-herring: it's `-Xswiftc -enable-testing` that causes the issue.

**Comment by thomasvl** [comment]
Revised to also fix failing case on 5.3 until the issue is resolved.

**Comment by Lukasa** [comment]
Oh, I'm sorry that this never circled around. I believe apple/swift#37487 should have fixed this, so recent versions of 5.4 should be fine to use.

**Comment by thomasvl** [comment]
Thanks, testing a PR to move back to latest (5.4.x) to see how things go.

**Pull request merged**
