### PR TITLE
Add public convenience property representing the name of the enum value

### PR DESCRIPTION
**Pull request by geor-kasapidi**

### CODE REVIEW

**Comment by allevato** [comment]
Thanks for using swift-protobuf!

We've made a conscious decision not to provide public APIs for converting enums to/from their string names—see #326 for much more discussion about this. In short, an API such as this one is not quite the correct venue for it to be expressed; it's essentially a special-case of a descriptor (which we don't support yet), and typically one should think about serializing entire messages into text format if that's what's needed, because the protobuf spec doesn't really make any statements (to my knowledge) about serializing an enum to text in isolation.

**Comment by geor-kasapidi** [comment]
@allevato thanks for your reply! Access to string representation of enum case is useful for API interaction. For example, in my case i have endpoints with protobuf responses and some plain text request parameters (query string, JSON data in body). And i need to pass enum case name as parameter value. As i see, i'm not first person who wants this functionality :) If code from my PR does not coincide with your vision of SwiftProtobuf future, maybe it makes sense to provide some meta information of Message, Enum, etc. For now, i see two options - fork this repo (bad idea), and second - use some reflection:

**Comment by EricRabil** [comment]
Being able to access this would've allowed me to easily log the name of the payload being processed, as I am using `oneof` to enumerate all possible IPC payloads. I think this is a more than acceptable use case, and it's upsetting that the library is still gatekeeping it.

IMO, this data has been sitting in the library for 5 years and counting. It clearly works well enough, even if it is "not quite correct" or a "special-case". If the alternative is reflection, which is not performant, why should this remain an internal API? More importantly, why is the library the only one with easy access to this information?

**Comment by thomasvl** [comment]
@EricRabil are you talking the name of the fields in a `oneof`?  If so that's different (it is field names in gneral), this issue was getting the `case` names from `enum`s.

**Comment by EricRabil** [comment]
Yes, good eye. I should've posted this in #731

**Comment by thomasvl** [comment]
fyi - That's still enum cases.  I don't think we've gotten a general request for field names/oneofs.

**Comment by EricRabil** [comment]
I can make one :D

**Pull request closed without merging**
