### PR TITLE
Includes protoc and plugin version in generated sources.

### PR DESCRIPTION
**Pull request by thomasvl**
Hopefully will help trouble shooting in the future as it leaves a
breadcrumb about generation.

Filter out the versions in the checked in files so as not to
cause a lot of churn within this project.

Fixes https://github.com/apple/swift-protobuf/issues/111

### CODE REVIEW

**Comment by thomasvl** [comment]
Having now implemented this, I'm of mixed feelings.

- Part of me feels like this is sorta like putting in date/time stamps; and something that makes it harder to have hermetic builds.  https://github.com/apple/swift-protobuf/issues/219 will add a something to cause mismatches to have compile errors, so I'm not completely sure how useful this info ends up being.
- Instead of the post processing sed, it could also be done via a undocumented compiler option (or env variable check?) that we set during generation.
- Currently I'm filtering all the generated source that is checked in, the real problem cases would seem to be the Reference directory, do we only want to post process there?

Thoughts?

**Comment by tbkka** [comment]
Good points.

Off the top of my head, here are a couple of possible alternatives:
* We could mitigate the churn problem by trimming the version info (just major.minor, leaving off the fine details).
* We could emit the detailed version info to stderr as build log information instead of putting it in the generated sources.  That would expose the information to people diagnosing build issues.  (Of course, some build systems interpret any output to stderr as evidence of a build failure.)

**Comment by thomasvl** [comment]
My fear would be when there is a problem, those point version matter; which likely would mean using the short version won't get us much.  When the short version does really change, odds are the work for #219 will call it out instead.

I'm a big fan a silent builds unless there is a problem.  If builds are chatty folks are more likely to miss real warnings/errors.

**Comment by allevato** [comment]
IMO, the version of `protoc` and `protoc-gen-swift` used to generate the protos seems less important than the compatibility version introduced in #234, which will encode a more meaningful (at least to the runtime, not necessarily to humans) version number in the source. So including the other version numbers seems like it would just make noisier diffs without a lot of value.

The argument could be made that the `protoc` version matters in situations where old compilers were broken (i.e., JSON names), but I'm not sure that happens frequently enough to worry about it here?

**Comment by thomasvl** [comment]
Even in the old protoc case, we're printing out a warning during generation.  Once could argue that warning might not be seen by folks, but we still don't have anything like `#warning`, so the best we could do is a generated comment if we want something to live in the file for these case.

Anyway, I'm on the fence.

**Comment by thomasvl** [comment]
@tbkka @allevato any verdict here?

I guess we can submit this as is, and also revisit it if the info proves to be a problem for folks using the plugin.

**Comment by allevato** [comment]
Sorry, thought I replied to this yesterday.

I don't see a problem with the way it's being done now. Every generated Swift file will contain the compatibility version now, which is probably more important than the specific protoc or protoc-gen-swift version.

**Comment by thomasvl** [comment]
I'll close this out without landing it can close off #111 since we do now issue warnings from the plugin.  If we find a need for it, we can always re-investigate something like this in the future.

**Pull request closed without merging**
