### PR TITLE
Disable swiftlint AND swift-format checking

### PR DESCRIPTION
**Pull request by tbkka**
We include a comment to suppress checking for swift-format.

Do the same for SwiftLint.

Note:  No, I really don't want this to proliferate.  The next time someone asks, I should probably tell them to talk to the tool vendor about recognizing other tools' comments.

### CODE REVIEW

**Review by thomasvl — APPROVED** [review]
All the golden tests are gonna fail until you do a regenerate and reference build.

**Comment by thomasvl** [comment]
@tbkka did you want to do the regeneration to land this?

**Comment by thomasvl** [comment]
@tbkka did you want to get this in?

**Comment by tbkka** [comment]
Thanks for the reminder!   I rebuilt everything and it should be good to go once the tests pass.

**Pull request merged**
