### PR TITLE
Avoid the generated code needing to capture the Extension default values twice.

### PR DESCRIPTION
**Pull request by thomasvl**

### CODE REVIEW

**Comment by thomasvl** [comment]
This ends up needing the defaultValue in two places:
1. Default protocol imp for extension lookup in ExtensibleMessage.
1. During the creation of a new field for decoding (decode is on the extension field).
Ideally, I'd change 1 so it returns nil and let the generator add the ?? default value.  That would let the default value not get created unless it was needed.  But the catch is 2.  We'd have to figure out how to redo decoding so it doesn't have to be done on the field, and instead can just deal with values and let the field get created after the fact.  The catch being extensions that are a message themselves, they would have to see if there in an existing value to do the merging if the field number is found twice.

**Comment by thomasvl** [comment]
Should I bump `compatibilityVersion` as part of this since there is some shuffling of what is generated?

**Comment by thomasvl** [comment]
It might make sense to move the decode from the ExtensionFields to MessageExtension( or MessageExtensionBase).  But just doing that would mean generating a custom decode for *every* extension, so we'd likely need to insert subclasses of MessageExtension for the generator to use like the ExtensionField ones so the decode methods really could be written once (and compile/linked once).

**Comment by thomasvl** [comment]
Anyway, this is pretty good progress on #502, and so lets get this in, and I'll see if I can find something to deal with the default values in the next few days.

**Comment by tbkka** [comment]
This is a nice cleanup.

Please do bump `compatibilityVersion` since this does change the API between the library and the generated code.

**Comment by thomasvl** [comment]
Added a commit to bump `compatibilityVersion`

**Pull request merged**
