### PR TITLE
Add a swift-format check to run on PRs.

### PR DESCRIPTION
**Pull request by thomasvl**
Based off the swift-nio ones.

### CODE REVIEW

**Comment by thomasvl** [comment]
Confirmed the check works with a edit in one of the pushes: https://github.com/apple/swift-protobuf/actions/runs/10965837593/job/30452496743

And https://github.com/apple/swift-protobuf/actions/runs/10965790445/job/30452355139 shows all the `swift format lint` warnings for why I disabled that.

**Comment by thomasvl** [comment]
@Lukasa gentle ping

**Comment by thomasvl** [comment]
All the other PRs that have landed have `lint` almost passing. The two things that remain would be api breaking and/or seem like bugs in `swift-format`, so I've upstreamed an issue for the bug (and the fact that suppressions don't seem to work).

**Comment by thomasvl** [comment]
gentle ping

**Review by tbkka — APPROVED** [review]
Nice work!

**Pull request merged**
