### PR TITLE
Start removing support for Swift < 5.6.

### PR DESCRIPTION
**Pull request by thomasvl**
NOTE: Swift 5.7 seems to be when `Data` got marked as `Sendable`, as a result
things still have to be marked as `@unchecked Sendable` until 5.7 (or later) is
the minimum supported version.

- Remove older Package@*.swift files.
- Update core library code to remove conditionals.

### CODE REVIEW

**Comment by thomasvl** [comment]
I'll do the OneOf changes generator changes after this, figured I'd make sure I had everything right with the `@unchecked` first in something a little smaller.

**Review by FranzBusch — COMMENTED** [review]
Can we enable strict concurrency checking in the CI as well with this

```
            swiftSettings: [
                .enableExperimentalFeature("StrictConcurrency=complete"),
            ]
```

We should also make sure `warnings-as-error` is enabled (probably is just double checking)

**Review by FranzBusch — APPROVED** [review]

**Comment by thomasvl** [comment]
> Can we enable strict concurrency checking in the CI as well with this
>
> ```
>             swiftSettings: [
>                 .enableExperimentalFeature("StrictConcurrency=complete"),
>             ]
> ```

Done.

@FranzBusch please take another look.

**Comment by thomasvl** [comment]
> We should pass it to swift test in our CI invocation. We do this for all our NIO repos

Ok, I think I've got this wired up now.

**Review by FranzBusch — APPROVED** [review]
Nice! Thanks

**Pull request merged**
