### PR TITLE
Customize Jazzy documentation generation

### PR DESCRIPTION
**Pull request by dpassage**
This adds a makefile step for building the documentation, using the same process/tool used by the CocoaPods ecosystem. It also slightly customizes the output to include those files in `Documentation` targeted at users of the library and plugin, rather than project contributors.

### CODE REVIEW

**Comment by thomasvl** [comment]
Showing my ignorance, will anything auto publish this, or do we need to put something (in the README.md?) point folks at how to get/find these full docs?

**Comment by dpassage** [comment]
This will get auto-published by the Cocoapods infrastructure once the podspec gets pushed to the public trunk, every time a new podspec gets published.

The `0.9.24` spec was published, so you can see the docs generated for that version here:

http://cocoadocs.org/docsets/SwiftProtobuf/0.9.24/

I think it may also be possible to make the compiled docs appear at a url like "http://apple.github.io/SwiftProtobuf" via the Github Pages stuff. But I think we'd need to check the built docs tree into the repo to get that to happen.

In any case, adding a link to README makes sense as well.

**Comment by thomasvl** [comment]
Oh, didn't realize it would run Jazzy, http://cocoadocs.org/readme/ just talks about restyling things.  ☹️

**Comment by dpassage** [comment]
Yeah, oddly enough, the documentation site isn't real well documented...

**Comment by allevato** [comment]
The good news is, those autogenerated docs point out a ton of places where we need to go back and add documentation to anything that's public. We can use that as a guide to tidy things up with full descriptions, or at a minimum, something that says "this is only public as an implementation requirement" where needed.

**Comment by dpassage** [comment]
You can also set it to only include symbols with documentation; that'll help with "hiding" things like the `_proto*` methods

**Comment by thomasvl** [comment]
Did you want to update this with an addition to the README.md?

**Comment by dpassage** [comment]
Sure, I'll add that to this PR this morning.

**Comment by dpassage** [comment]
OK, link added!

**Comment by dpassage** [comment]
thanks!

**Comment by thomasvl** [comment]
> thanks!

np, thank you for the patch!

**Comment by thomasvl** [comment]
Finally got around to installing jazzy to look at things, and it is choking when running:

```
$ make docs
Using config file /Users/thomasvl/src/github/swift-protobuf/.jazzy.yaml
/Users/thomasvl/.gem/gems/jazzy-0.7.4/lib/jazzy/config.rb:431:in `read_config_file': undefined method `safe_load' for Psych:Module (NoMethodError)
	from /Users/thomasvl/.gem/gems/jazzy-0.7.4/lib/jazzy/config.rb:393:in `parse_config_file'
	from /Users/thomasvl/.gem/gems/jazzy-0.7.4/lib/jazzy/config.rb:341:in `parse!'
	from /Users/thomasvl/.gem/gems/jazzy-0.7.4/bin/jazzy:15:in `<top (required)>'
	from /Users/thomasvl/.gem/bin/jazzy:23:in `load'
	from /Users/thomasvl/.gem/bin/jazzy:23:in `<main>'
make: *** [docs] Error 1
```

The `gem install jazzy` seemed fine, but it did print out some warnings:

```
$ gem install jazzy
Fetching: mustache-0.99.8.gem (100%)
Successfully installed mustache-0.99.8
Fetching: open4-1.3.4.gem (100%)
Successfully installed open4-1.3.4
Fetching: redcarpet-3.4.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed redcarpet-3.4.0
Fetching: rouge-1.11.1.gem (100%)
Successfully installed rouge-1.11.1
Fetching: sass-3.4.23.gem (100%)
Successfully installed sass-3.4.23
Fetching: liferaft-0.0.6.gem (100%)
Successfully installed liferaft-0.0.6
Fetching: xcinvoke-0.3.0.gem (100%)
Successfully installed xcinvoke-0.3.0
Fetching: jazzy-0.7.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed jazzy-0.7.4
Fetching: cocoapods-core-1.2.0.gem (100%)
Successfully installed cocoapods-core-1.2.0
Fetching: molinillo-0.5.7.gem (100%)
Successfully installed molinillo-0.5.7
Fetching: ruby-macho-0.2.6.gem (100%)
Successfully installed ruby-macho-0.2.6
Parsing documentation for mustache-0.99.8
Installing ri documentation for mustache-0.99.8
Parsing documentation for open4-1.3.4
Installing ri documentation for open4-1.3.4
Parsing documentation for redcarpet-3.4.0
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/redcarpet.bundle, skipping
Installing ri documentation for redcarpet-3.4.0
Parsing documentation for rouge-1.11.1
Installing ri documentation for rouge-1.11.1
Parsing documentation for sass-3.4.23
Installing ri documentation for sass-3.4.23
Parsing documentation for liferaft-0.0.6
Installing ri documentation for liferaft-0.0.6
Parsing documentation for xcinvoke-0.3.0
Installing ri documentation for xcinvoke-0.3.0
Parsing documentation for jazzy-0.7.4
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/SourceKittenFramework, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Commandant, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/Current/Commandant, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Result, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions/A/Result, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions/Current/Result, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/SWXMLHash, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/A/SWXMLHash, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/Current/SWXMLHash, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions/A/Yams, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions/Current/Yams, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Yams, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftCore.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftCoreGraphics.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftDarwin.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftDispatch.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftFoundation.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftIOKit.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftObjectiveC.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/A/SourceKittenFramework, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Commandant.framework/Commandant, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Commandant.framework/Versions/A/Commandant, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Commandant.framework/Versions/Current/Commandant, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Result.framework/Result, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Result.framework/Versions/Current/Result, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/SWXMLHash.framework/SWXMLHash, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/SWXMLHash.framework/Versions/A/SWXMLHash, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/SWXMLHash.framework/Versions/Current/SWXMLHash, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Yams.framework/Versions/A/Yams, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Yams.framework/Versions/Current/Yams, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/Yams.framework/Yams, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/libswiftCore.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/libswiftCoreGraphics.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/libswiftDarwin.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/libswiftDispatch.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/libswiftFoundation.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/libswiftIOKit.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks/libswiftObjectiveC.dylib, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/Versions/Current/SourceKittenFramework, skipping
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/bin/sourcekitten, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/jazzy/themes/apple/assets/img/carat.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/jazzy/themes/apple/assets/img/dash.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/jazzy/themes/apple/assets/img/gh.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/jazzy/themes/fullwidth/assets/img/carat.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/jazzy/themes/fullwidth/assets/img/dash.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/jazzy/themes/fullwidth/assets/img/gh.png, skipping
unable to convert "\xF4" from ASCII-8BIT to UTF-8 for lib/jazzy/themes/fullwidth/assets/img/spinner.gif, skipping
Installing ri documentation for jazzy-0.7.4
Parsing documentation for cocoapods-core-1.2.0
Installing ri documentation for cocoapods-core-1.2.0
Parsing documentation for molinillo-0.5.7
Installing ri documentation for molinillo-0.5.7
Parsing documentation for ruby-macho-0.2.6
Installing ri documentation for ruby-macho-0.2.6
11 gems installed
```

**Comment by thomasvl** [comment]
Looks like it is https://github.com/realm/jazzy/issues/747, but I guess there hasn't been a jazzy release to push this out.

**Comment by dpassage** [comment]
Hm, I didn't run into it because I'm using a newer version of `ruby`. The system `ruby` on Sierra is still back at 2.0.0, which is pretty long in the tooth at this point.

We could add a `Gemfile` to point at the tip of `master` for `jazzy` to address this.

**Comment by thomasvl** [comment]
New version [just cut](https://github.com/realm/jazzy/pull/748#issuecomment-288138807), not sure when it will show when installing jazzy.

**Pull request merged**
