### PR TITLE
Add 5.0.x build to coverage.

### PR DESCRIPTION
**Pull request by thomasvl**
Let the matrix auto generate and just insert the one special case for 4.2.

### CODE REVIEW

**Comment by thomasvl** [comment]
Hm, was the 5.0 image bad in that it is missing zlib or something?

**Comment by tbkka** [comment]
I suppose we could try adding `zlib-dev` to the `apt-get install` line to ensure it's there?

**Comment by thomasvl** [comment]
Looks like `zlib-dev` doesn't exist.  Looking at the [packages providing the header](https://packages.ubuntu.com/search?searchon=contents&keywords=zlib.h&mode=exactfilename&suite=eoan&arch=any), I'm not sure if one of those is safe to pick without getting extra dependencies by accident.

**Comment by thomasvl** [comment]
ps - I'm trying to figure out how to get 5.0.x added because when 5.3 ships, our min _toolchain_ would be 4.3, which doesn't exist, so having something on 5.0 would get us that older coverage.

**Comment by tbkka** [comment]
You want `zlib1g-dev`

**Comment by thomasvl** [comment]
Thanks, that seems to have worked.

**Pull request merged**
