### PR TITLE
var --> let to eliminate warning

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Comment by thomasvl** [comment]
Which toolchain version is getting this warning?  We don't see to be getting it.

**Comment by brettkoonce** [comment]
coming from 1.7.0, sorry about that!
https://github.com/tensorflow/swift-models/blob/a3bcac81b45fb94cf52ecaf273978cf45dd7158d/Package.swift#L39

**Comment by brettkoonce** [comment]
still hitting this when building swift-models packages, fwiw.  used 1.9.0 checkout and still getting same error:

/home/skoonce/swift/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:198:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/home/skoonce/swift/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:198:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let
/home/skoonce/swift/swift-models/.build/checkouts/swift-protobuf/Sources/SwiftProtobuf/BinaryDelimited.swift:198:7: warning: variable 'readBuffer' was never mutated; consider changing to 'let' constant
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let

**Comment by thomasvl** [comment]
Looking at your mentioned tensorflow/swift-models#569, it doesn't update `Packages.resolved`, so aren't you still using the old version?

**Comment by brettkoonce** [comment]
deleted Packages.resolved + .build directory, ran, still seeing this!

**Comment by thomasvl** [comment]
What toolchain version, os, etc. are you on since we don't seem to be seeing this?

**Comment by brettkoonce** [comment]
Linux 18.04, s4tf master build (tweaks + 5.3 tip), swift-models master branch.

```
swift --version
Swift version 5.3-dev (LLVM a2905f3b8d, Swift 112f6d30ba)
Target: x86_64-unknown-linux-gnu

which swift
/home/skoonce/swift/swift-source/swift/swift-nightly-install/usr/bin/swift
```

**Comment by thomasvl** [comment]
I wonder if this is specific to the s4tf build in some way…

**Comment by thomasvl** [comment]
Thanks!

**Pull request merged**
