### PR TITLE
Enable Swift-DocC plugin for generating docs

### PR DESCRIPTION
**Pull request by tbkka**
I'm going to be going through things and updating our API docs and articles to work cleanly with DocC.  First step is to make it easier to build and view the docs.

With this, you can build and view the docs for a single part of our project with:
```
% swift package --disable-sandbox preview-documentation --target SwiftProtobuf   
```
This should also work for `--target protoc-gen-swift`, `--target SwiftProtobufPluginLibrary`, and `--target Conformance`.

### CODE REVIEW

**Review by thomasvl — COMMENTED** [review]
Should we document how to do any of this?  Is it worth running any sorta CI to catch issue with source comments/etc?

Showing my ignorance, how does this compare to `xcodebuild docbuild`? (https://developer.apple.com/documentation/xcode/distributing-documentation-to-external-developers)

**Comment by thomasvl** [comment]
I guess I'm also sorta think of #1154 and #1032, should we start linking to other things and maybe dropping the jazzy info in the repo?

**Comment by tbkka** [comment]
This uses exactly the same tools as `xcodebuild docbuild` and should produce identical results.  The only difference is that it will work on non-Apple platforms.

I don't think we're ready to drop Jazzy support just yet.  I plan to spend some time over the next few weeks trying to clean up and improve the DocC docs.

**Comment by thomasvl** [comment]
> I plan to spend some time over the next few weeks trying to clean up and improve the DocC docs.

Great!  You might want to self assign those two issues then to let folks know things are being worked on.

**Review by thomasvl — APPROVED** [review]

**Pull request merged**
